[pytest]
filterwarnings =
    ignore:.*is a deprecated alias.*:DeprecationWarning
    ignore:.*invalid escape sequence.*:DeprecationWarning

tmp_path_retention_count = 10

# --tb not given    Produces reams of output, with full source code included in tracebacks
# --tb=no           Just shows location of failure in the test file: no use for tracking down errors
# --tb=short        Just shows vanilla traceback: very useful, but file names are incomplete and relative
# --tb=native       Slightly more info than short: still works very well. The full paths may be useful for CI
addopts = --tb=no
