syntax = "proto3";

package dunedaq.dfmodules.opmon;


// regular metric published byt the DFO
message DFOInfo {
  // status metrics
  uint64 pending_trigger_decisions = 1; // Present number of TriggerDecisions being worked on by the dataflow

  // counters
  uint64 statuses_received = 20;
  uint64 decisions_received = 21;
  uint64 decisions_sent = 22;
  uint64 decisions_completed = 23;

  // time management of the decision thread
  uint64 waiting_for_decision = 30 ; // Time spent waiting on Trigger Decisions, in microseconds
  uint64 deciding_destination = 31 ; // Time spent making a decision on the receving DF app, in microseconds
  uint64 forwarding_decision = 32  ; // Time spent sending the Trigger Decision to TRBs, in microseconds

}


// these counters are published separately for each trigger type
message TriggerInfo {

  uint64 received = 1;
  uint64 completed = 2;
}