syntax = "proto3";

package dunedaq.dfmodules.opmon;

message FADataRequestsCounterInfo {

  uint64 data_requests_received = 1;
  uint64 data_requests_processed = 2;
  uint64 data_requests_failed = 3;

}

message FAFragmentsCounterInfo {

  uint64 fragments_received = 1;
  uint64 fragments_processed = 2;
  uint64 fragments_failed = 3;
  uint64 fragments_empty = 4;
  uint64 fragments_incomplete = 5;
  uint64 fragments_invalid = 6;

}

message FragmentAggregatorTimeInfo {

  uint64 average_us = 1;
  uint64 min_us = 2;
  uint64 max_us = 3;

}
